name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build web version in Docker
      - name: Build web version in Docker
        run: |
          docker build -t frontend-builder -f Dockerfile.front .
          docker create --name build-container frontend-builder
          docker cp build-container:/app/dist ./dist
          docker rm build-container

      # Build Home Assistant version
      - name: Build Home Assistant version
        run: |
          docker build -t ha-builder -f Dockerfile.front --build-arg BUILD_COMMAND=build:ha .
          docker create --name ha-build-container ha-builder
          docker cp ha-build-container:/app/custom_components ./custom_components
          docker rm ha-build-container

      # Add CNAME file for web version
      - name: Add CNAME file
        run: echo "transport.dzarlax.dev" > ./dist/CNAME

      # Deploy web version to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      # Create Home Assistant release
      - name: Create Home Assistant Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      # Zip Home Assistant integration
      - name: Zip Home Assistant integration
        run: |
          cd custom_components
          zip -r ../city-dashboard.zip city_dashboard/

      # Upload Home Assistant integration to release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./city-dashboard.zip
          asset_name: city-dashboard.zip
          asset_content_type: application/zip