name: Build and Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main # Запуск при пуше в main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Сборка фронтенда в Docker
      - name: Build static files in Docker
        run: |
          docker build -t frontend-builder -f Dockerfile.front .
          docker create --name build-container frontend-builder
          docker cp build-container:/app/dist ./dist
          docker rm build-container

      # Шаг 3: Добавление CNAME файла
      - name: Add CNAME file
        run: echo "transport.dzarlax.dev" > ./dist/CNAME

      # Шаг 4: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Указываем ветку для деплоя